// Code generated by "stringer -type=Type"; DO NOT EDIT

package tzsp

import "fmt"

const _Type_name = "TypeReceivedTagListTypePacketForTransmitTypeReservedTypeConfigurationTypeKeepAliveTypePortOpener"

var _Type_index = [...]uint8{0, 19, 40, 52, 69, 82, 96}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
